// Sample data for the anime gallery
const animeImages = [
  {
    id: 1,
    title: "1girl artist_name be...",
    src: "/images/sample1.png",
    owner: "danbooru",
    size: "2048 x 1152",
    status: "active",
    rating: "general",
    comments: 0,
    tags: ["red_eyes", "thighhighs", "dress", "persona_4", "jewelry", "standing", "hair_ornament", "closed_mouth"],
  },
  {
    id: 2,
    title: "2girls a_fragment_of...",
    src: "/images/sample2.png",
    owner: "danbooru",
    size: "1920 x 1080",
    status: "active",
    rating: "general",
    comments: 5,
    tags: ["2girls", "arms_behind_back", "long_hair", "blue_cape", "cape", "cleo_(dragalia_lost)", "commission"],
  },
  {
    id: 3,
    title: "1girl ascot blonde_h...",
    src: "/images/sample3.png",
    owner: "danbooru",
    size: "1600 x 900",
    status: "active",
    rating: "general",
    comments: 2,
    tags: ["1girl", "ascot", "blonde_hair", "drill_hair", "fingerless_gloves", "gloves", "hair_bell", "hair_ornament"],
  },
  {
    id: 4,
    title: "1boy arms_up black_b...",
    src: "/images/sample4.png",
    owner: "danbooru",
    size: "1800 x 1200",
    status: "active",
    rating: "general",
    comments: 8,
    tags: ["1boy", "arms_up", "black_background", "very_long_hair", "vgen_commission", "holding_staff", "long_sleeves"],
  },
  {
    id: 5,
    title: "1girl blue_eyes long...",
    src: "/placeholder.svg?height=300&width=250",
    owner: "danbooru",
    size: "1920 x 1080",
    status: "active",
    rating: "general",
    comments: 3,
    tags: ["1girl", "blue_eyes", "long_hair", "school_uniform", "smile", "cherry_blossoms"],
  },
  {
    id: 6,
    title: "2girls pink_hair tw...",
    src: "/placeholder.svg?height=280&width=250",
    owner: "danbooru",
    size: "1600 x 1200",
    status: "active",
    rating: "general",
    comments: 12,
    tags: ["2girls", "pink_hair", "twin_tails", "magical_girl", "wand", "sparkles"],
  },
  {
    id: 7,
    title: "1boy sword armor...",
    src: "/placeholder.svg?height=320&width=250",
    owner: "danbooru",
    size: "2048 x 1536",
    status: "active",
    rating: "general",
    comments: 7,
    tags: ["1boy", "sword", "armor", "fantasy", "cape", "serious_expression"],
  },
  {
    id: 8,
    title: "1girl cat_ears neko...",
    src: "/placeholder.svg?height=290&width=250",
    owner: "danbooru",
    size: "1440 x 1080",
    status: "active",
    rating: "general",
    comments: 15,
    tags: ["1girl", "cat_ears", "neko", "tail", "cute", "maid_outfit"],
  },
]

const tagColors = {
  red_eyes: "tag-red",
  thighhighs: "tag-purple",
  dress: "tag-pink",
  persona_4: "tag-orange",
  jewelry: "tag-cyan",
  standing: "tag-blue",
  hair_ornament: "tag-green",
  closed_mouth: "tag-indigo",
  "2girls": "tag-purple",
  arms_behind_back: "tag-blue",
  long_hair: "tag-green",
  blue_cape: "tag-blue",
  cape: "tag-indigo",
  commission: "tag-orange",
  "1girl": "tag-pink",
  ascot: "tag-red",
  blonde_hair: "tag-orange",
  drill_hair: "tag-purple",
  fingerless_gloves: "tag-cyan",
  gloves: "tag-blue",
  hair_bell: "tag-green",
  "1boy": "tag-indigo",
  arms_up: "tag-red",
  black_background: "tag-purple",
  very_long_hair: "tag-green",
  vgen_commission: "tag-orange",
  holding_staff: "tag-cyan",
  long_sleeves: "tag-blue",
  blue_eyes: "tag-blue",
  school_uniform: "tag-indigo",
  smile: "tag-pink",
  cherry_blossoms: "tag-pink",
  pink_hair: "tag-pink",
  twin_tails: "tag-purple",
  magical_girl: "tag-pink",
  wand: "tag-orange",
  sparkles: "tag-cyan",
  sword: "tag-red",
  armor: "tag-indigo",
  fantasy: "tag-purple",
  serious_expression: "tag-red",
  cat_ears: "tag-orange",
  neko: "tag-orange",
  tail: "tag-green",
  cute: "tag-pink",
  maid_outfit: "tag-purple",
}
